apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  annotations:
    run.googleapis.com/ingress: all
    run.googleapis.com/launch-stage: BETA
    run.googleapis.com/description: web multi-container service
    run.googleapis.com/ingress-status: all
    run.googleapis.com/minScale: "1"
  labels:
    cloud.googleapis.com/location: asia-northeast1
  name: web
  namespace: "1055660352976"
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/maxScale: "100"
        autoscaling.knative.dev/minScale: "1"
        run.googleapis.com/client-name: gcloud
        run.googleapis.com/client-version: 484.0.0
        run.googleapis.com/startup-cpu-boost: "true"
        # 默认生成的容器名为 web-1
        run.googleapis.com/container-dependencies: "{nginx: [web-1]}"
      labels:
        client.knative.dev/nonce: cpfzaxdngx
        run.googleapis.com/startupProbeType: Default
    spec:
      containerConcurrency: 80
      containers:
        - image: nginx
          name: nginx
          ports:
            - name: http1
              containerPort: 8080
          resources:
            limits:
              cpu: 500m
              memory: 256Mi
          # Referencing declared volume below,
          # Declaring volume to mount in current ingress container's filesystem
          # https://cloud.google.com/run/docs/reference/rest/v2/Container#volumemount
          volumeMounts:
            - name: nginx-conf-secret
              readOnly: true
              mountPath: /etc/nginx/conf.d/
          startupProbe:
            timeoutSeconds: 240
            periodSeconds: 240
            failureThreshold: 1
            tcpSocket:
              port: 8080

        - image: asia-northeast1-docker.pkg.dev/central-beach-430219-e4/web-application-template/web
          # 默认生成的容器名为 web-1
          name: web-1
          env:
            - name: PORT
              value: "8888"
          resources:
            limits:
              cpu: 1000m
              memory: 512Mi
          startupProbe:
            failureThreshold: 1
            periodSeconds: 240
            tcpSocket:
              port: 8888
            timeoutSeconds: 240

      volumes:
        - name: nginx-conf-secret
          secret:
            secretName: nginx_config
            items:
              - key: latest
                path: default.conf

      serviceAccountName: cloud-run-deploy@central-beach-430219-e4.iam.gserviceaccount.com
      timeoutSeconds: 300
  traffic:
    - latestRevision: true
      percent: 100
